name: build

enable-openid-connect: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    runs-on: alpine
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/go-setup@master
      - uses: actions/toolkit/go-test@master
  container:
    runs-on: alpine
    needs: [test]
    steps:
      - uses: actions/toolkit/git-checkout@master
      - uses: actions/toolkit/docker-login@master
        with:
          audience: u:1:224a368c-1b2e-426f-b063-61f6fbafc2a7
      - uses: actions/toolkit/docker-push@master
        with:                                                                                                                                                                    
          tags: git.mouse-lake.ts.net/${{ github.repository }}:latest
