name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  - name: test
    uses: greboid/.github/.github/workflows/checkout-and-test-go.yml@master
    secrets: inherit
  - name: container
    uses: greboid/.github/.github/workflows/checkout-build-and-push-docker.yml@master
    with:
      registry: ${{ secrets.REGISTRY }}
    secrets: inherit
    needs: [test]
