name: build
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  test:
    uses: greboid/.github/.github/workflows/go-test.yml@master
    secrets: inherit
  container:
    uses: greboid/.github/.github/workflows/docker.yml@master
    with:
      registry: 'reg.g5d.dev'
    secrets: inherit
    needs: [ test ]
